import type { Metadata } from "next";
import "./globals.css";
import RandomRefresh from "@/components/RandomRefresh";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<RandomRefresh />
			<body>{children}</body>
		</html>
	);
}
